def junctions
    [
        {
            "id":1 ,
            "top":459 ,
            "left":1747,
            "surroundings": %w[main-gate]
        },
        {
            "id":2,
            "top":602,
            "left":1757,
            "surroundings": %w[guest-house]
        },
        {
            "id":3,
            "top":833,
            "left":1763,
            "surroundings": []
        },
        {
            "id":4,
            "top":839,
            "left":1763,
            "surroundings": []
        },
        {
            "id":5,
            "top":919,
            "left":1777,
            "surroundings": %w[atm-1]
        },
        {
            "id":6,
            "top":956,
            "left":1828,
            "surroundings": %w[main-parking]
        },
        {
            "id":7,
            "top":1174,
            "left":1785,
            "surroundings": []
        },
        {
            "id":8,
            "top":1173,
            "left":1849,
            "surroundings": []
        },
        {
            "id":9,
            "top":1157,
            "left":2111,
            "surroundings": %w[lake]
        },
        {
            "id":10,
            "top":1231,
            "left":1782,
            "surroundings": []
        },
        {
            "id":11,
            "top":1238,
            "left":1521,
            "surroundings": %w[bus]
        },
        {
            "id":12,
            "top":1270,
            "left":859,
            "surroundings": %w[staff-quarters]
        },
        {
            "id":13,
            "top":1288,
            "left":339,
            "surroundings": %w[west-gate-staffs]
        },
        {
            "id":14,
            "top":1462,
            "left":1535,
            "surroundings": %w[smart-agri-fields]
        },
        {
            "id":15,
            "top":1401,
            "left":1789,
            "surroundings": []
        },
        {
            "id":16,
            "top":1413,
            "left":1895,
            "surroundings": %w[principal-office reserach-park]
        },
        {
            "id":17,
            "top":1451,
            "left":1800,
            "surroundings":%w[]
        },
        {
            "id":18,
            "top":1448,
            "left":1898,
            "surroundings":%w[]
        },
        {
            "id":19,
            "top":1635,
            "left":1797,
            "surroundings":%w[]
        },
        {
            "id":20,
            "top":1645,
            "left":1976,
            "surroundings":%w[principal-room dean-room]
        },
        {
            "id":21,
            "top":1726,
            "left":1813,
            "surroundings":%w[]
        },
        {
            "id":22,
            "top":1726,
            "left":1977,
            "surroundings":%w[]
        },
        {
            "id":23,
            "top":1795,
            "left":1808,
            "surroundings":%w[]
        },
        {
            "id":24,
            "top":1804,
            "left":1987,
            "surroundings":%w[]
        },
        {
            "id":25,
            "top":1905,
            "left":1915,
            "surroundings":%w[]
        },
        {
            "id":26,
            "top":1919,
            "left":1999,
            "surroundings":%w[sf-block]
        },
        {
            "id":27,
            "top":1984,
            "left":1830,
            "surroundings":%w[]
        },
        {
            "id":28,
            "top":2025,
            "left":1829,
            "surroundings":%w[]
        },
        {
            "id":29,
            "top":2086,
            "left":1832,
            "surroundings":%w[]
        },
        {
            "id":30,
            "top":2045,
            "left":2062,
            "surroundings":%w[]
        },
        {
            "id":31,
            "top":1969,
            "left":2145,
            "surroundings":%w[sf-block-labs]
        },
        {
            "id":32,
            "top":2132,
            "left":1819,
            "surroundings":%w[]
        },
        {
            "id":33,
            "top":2129,
            "left":1904,
            "surroundings":%w[]
        },
        {
            "id":34,
            "top":2166,
            "left":1899,
            "surroundings":%w[mechanic-front]
        },
        {
            "id":35,
            "top":2197,
            "left":1905,
            "surroundings":%w[]
        },
        {
            "id":36,
            "top":2197,
            "left":1839,
            "surroundings":%w[]
        },
        {
            "id":37,
            "top":2234,
            "left":1835,
            "surroundings":%w[]
        },
        {
            "id":38,
            "top":2277,
            "left":1843,
            "surroundings":%w[]
        },
        {
            "id":39,
            "top":2255,
            "left":2099,
            "surroundings":%w[]
        },
        {
            "id":40,
            "top":2215,
            "left":2093,
            "surroundings":%w[mechanic-back]
        },
        {
            "id":41,
            "top":2434,
            "left":1832,
            "surroundings":%w[]
        },
        {
            "id":42,
            "top":2462,
            "left":1834,
            "surroundings":%w[]
        },
        {
            "id":43,
            "top":2458,
            "left":1912,
            "surroundings":%w[]
        },
        {
            "id":44,
            "top":2514,
            "left":1922,
            "surroundings":%w[main-store]
        },
        {
            "id":45,
            "top":2567,
            "left":1920,
            "surroundings":%w[]
        },
        {
            "id":46,
            "top":2534,
            "left":1837,
            "surroundings":%w[]
        },
        {
            "id":47,
            "top":2570,
            "left":1839,
            "surroundings":%w[]
        },
        {
            "id":48,
            "top":2627,
            "left":1836,
            "surroundings":%w[main-store]
        },
        {
            "id":49,
            "top":2781,
            "left":1848,
            "surroundings":%w[]
        },
        {
            "id":50,
            "top":2767,
            "left":1981,
            "surroundings":%w[boys-visitor-hall]
        },
        {
            "id":51,
            "top":2761,
            "left":2022,
            "surroundings":%w[boys-hostels]
        },
        {
            "id":52,
            "top":2701,
            "left":2010,
            "surroundings":%w[indoor-gym]
        },
        {
            "id":53,
            "top":2753,
            "left":2070,
            "surroundings":%w[]
        },
        {
            "id":54,
            "top":2695,
            "left":2109,
            "surroundings":%w[]
        },
        {
            "id":55,
            "top":2669,
            "left":2066,
            "surroundings":%w[outdoor-gym]
        },
        {
            "id":56,
            "top":2669,
            "left":2131,
            "surroundings":%w[]
        },
        {
            "id":57,
            "top":2539,
            "left":2135,
            "surroundings":%w[]
        },
        {
            "id":58,
            "top":2530,
            "left":2061,
            "surroundings":%w[]
        },
        {
            "id":59,
            "top":2534,
            "left":2003,
            "surroundings":%w[coral]
        },
        {
            "id":60,
            "top":2535,
            "left":2196,
            "surroundings":%w[]
        },
        {
            "id":61,
            "top":2762,
            "left":2126,
            "surroundings":%w[]
        },
        {
            "id":62,
            "top":2754,
            "left":2231,
            "surroundings":%w[boys-mess]
        },
        {
            "id":63,
            "top":2563,
            "left":2240,
            "surroundings":%w[emerald]
        },
        {
            "id":64,
            "top":2504,
            "left":2307,
            "surroundings":%w[]
        },
        {
            "id":65,
            "top":2489,
            "left":2636,
            "surroundings":%w[diamond]
        },
        {
            "id":66,
            "top":2919,
            "left":2259,
            "surroundings":%w[sapphire]
        },
        {
            "id":67,
            "top":2952,
            "left":2235,
            "surroundings":%w[]
        },
        {
            "id":68,
            "top":2961,
            "left":2102,
            "surroundings":%w[]
        },
        {
            "id":69,
            "top":2964,
            "left":2047,
            "surroundings":%w[boys-canteen]
        },
        {
            "id":70,
            "top":2876,
            "left":2108,
            "surroundings":%w[boys-laundry]
        },
        {
            "id":71,
            "top":2968,
            "left":2418,
            "surroundings":%w[]
        },
        {
            "id":72,
            "top":2896,
            "left":2567,
            "surroundings":%w[]
        },
        {
            "id":73,
            "top":2882,
            "left":2637,
            "surroundings":%w[]
        },
        {
            "id":74,
            "top":3040,
            "left":2521,
            "surroundings":%w[]
        },
        {
            "id":75,
            "top":3030,
            "left":2665,
            "surroundings":%w[ruby]
        },
        {
            "id":76,
            "top":3040,
            "left":2934,
            "surroundings":%w[]
        },
        {
            "id":77,
            "top":3217,
            "left":2933,
            "surroundings":%w[]
        },
        {
            "id":78,
            "top":3240,
            "left":2883,
            "surroundings":%w[pearl]
        },
        {
            "id":79,
            "top":3268,
            "left":2517,
            "surroundings":%w[agri-playground]
        },
        {
            "id":80,
            "top":3278,
            "left":2285,
            "surroundings":%w[]
        },
        {
            "id":81,
            "top":3291,
            "left":1872,
            "surroundings":%w[playground-1]
        },
        {
            "id":82,
            "top":3108,
            "left":1852,
            "surroundings":%w[tennis-court-1 tennis-court-2 basket-ball-court volley-ball-court]
        },
        {
            "id":83,
            "top":2792,
            "left":1630,
            "surroundings":%w[]
        },
        {
            "id":84,
            "top":2790,
            "left":1593,
            "surroundings":%w[]
        },
        {
            "id":85,
            "top":2792,
            "left":1550,
            "surroundings":%w[]
        },
        {
            "id":86,
            "top":2902,
            "left":1551,
            "surroundings":%w[dayscholar-mess-1 recreation-hall]
        },
        {
            "id":87,
            "top":2902,
            "left":1632,
            "surroundings":%w[dayscholar-mess-2 pet-room cafeteria]
        },
        {
            "id":88,
            "top":2643,
            "left":1584,
            "surroundings":%w[]
        },
        {
            "id":89,
            "top":2591,
            "left":1584,
            "surroundings":%w[fashion-centre spinning-lab]
        },
        {
            "id":90,
            "top":2552,
            "left":1584,
            "surroundings":%w[]
        },
        {
            "id":91,
            "top":2491,
            "left":1582,
            "surroundings":%w[as-rib-11 as-rib-12]
        },
        {
            "id":92,
            "top":2451,
            "left":1579,
            "surroundings":%w[]
        },
        {
            "id":93,
            "top":2410,
            "left":1576,
            "surroundings":%w[as-rib-9 as-rib-10]
        },
        {
            "id":94,
            "top":2328,
            "left":1569,
            "surroundings":%w[]
        },
        {
            "id":95,
            "top":2283,
            "left":1574,
            "surroundings":%w[as-rib-7 as-rib-8]
        },
        {
            "id":96,
            "top":2241,
            "left":1568,
            "surroundings":%w[]
        },
        {
            "id":97,
            "top":2206,
            "left":1568,
            "surroundings":%w[as-rib-5 as-rib-6]
        },
        {
            "id":98,
            "top":2101,
            "left":1563,
            "surroundings":%w[]
        },
        {
            "id":99,
            "top":2066,
            "left":1563,
            "surroundings":%w[as-rib-3 as-rib-4]
        },
        {
            "id":100,
            "top":2024,
            "left":1561,
            "surroundings":%w[]
        },
        {
            "id":101,
            "top":1975,
            "left":1558,
            "surroundings":%w[as-rib-1 as-rib-2]
        },
        {
            "id":102,
            "top":1838,
            "left":1554,
            "surroundings":%w[]
        },
        {
            "id":103,
            "top":1832,
            "left":1588,
            "surroundings":%w[]
        },
        {
            "id":104,
            "top":1794,
            "left":1592,
            "surroundings":%w[as-main-right]
        },
        {
            "id":105,
            "top":1765,
            "left":1584,
            "surroundings":%w[]
        },
        {
            "id":106,
            "top":1770,
            "left":1553,
            "surroundings":%w[]
        },
        {
            "id":107,
            "top":1772,
            "left":1523,
            "surroundings":%w[]
        },
        {
            "id":108,
            "top":1835,
            "left":1518,
            "surroundings":%w[as-main-left]
        },
        {
            "id":109,
            "top":1715,
            "left":1540,
            "surroundings":%w[]
        },
        {
            "id":110,
            "top":1651,
            "left":1569,
            "surroundings":%w[]
        },
        {
            "id":111,
            "top":1652,
            "left":1527,
            "surroundings":%w[]
        },
        {
            "id":112,
            "top":1656,
            "left":1496,
            "surroundings":%w[]
        },
        {
            "id":113,
            "top":1656,
            "left":1350,
            "surroundings":%w[]
        },
        {
            "id":114,
            "top":2106,
            "left":1370,
            "surroundings":%w[]
        },
        {
            "id":115,
            "top":2104,
            "left":1451,
            "surroundings":%w[chiller-plant]
        },
        {
            "id":116,
            "top":2323,
            "left":1385,
            "surroundings":%w[]
        },
        {
            "id":117,
            "top":2422,
            "left":1388,
            "surroundings":%w[main-auditorium]
        },
        {
            "id":118,
            "top":2789,
            "left":1402,
            "surroundings":%w[library]
        },
        {
            "id":119,
            "top":2795,
            "left":1191,
            "surroundings":%w[]
        },
        {
            "id":120,
            "top":2660,
            "left":1194,
            "surroundings":%w[]
        },
        {
            "id":121,
            "top":2613,
            "left":1194,
            "surroundings":%w[placement-and-training internet-centre]
        },
        {
            "id":122,
            "top":2570,
            "left":1193,
            "surroundings":%w[]
        },
        {
            "id":123,
            "top":2521,
            "left":1192,
            "surroundings":%w[ib-rib-12 ib-rib-11]
        },
        {
            "id":124,
            "top":2461,
            "left":1193,
            "surroundings":%w[]
        },
        {
            "id":125,
            "top":2425,
            "left":1190,
            "surroundings":%w[ib-rib-10 ib-rib-9]
        },
        {
            "id":126,
            "top":2341,
            "left":1186,
            "surroundings":%w[]
        },
        {
            "id":127,
            "top":2298,
            "left":1181,
            "surroundings":%w[ib-rib-8 ib-rib-7]
        },
        {
            "id":128,
            "top":2255,
            "left":1181,
            "surroundings":%w[]
        },
        {
            "id":129,
            "top":2211,
            "left":1177,
            "surroundings":%w[ib-rib-6 ib-rib-5]
        },
        {
            "id":130,
            "top":2129,
            "left":1172,
            "surroundings":%w[]
        },
        {
            "id":131,
            "top":2001,
            "left":1163,
            "surroundings":%w[ib-rib-4 ib-rib-3]
        },
        {
            "id":132,
            "top":2036,
            "left":1168,
            "surroundings":%w[]
        },
        {
            "id":133,
            "top":2008,
            "left":1166,
            "surroundings":%w[ib-rib-1 ib-rib-2]
        },
        {
            "id":134,
            "top":1943,
            "left":1163,
            "surroundings":%w[herbal-garden]
        },
        {
            "id":135,
            "top":1849,
            "left":1159,
            "surroundings":%w[]
        },
        {
            "id":136,
            "top":1842,
            "left":1192,
            "surroundings":%w[ib-block-1]
        },
        {
            "id":137,
            "top":1781,
            "left":1191,
            "surroundings":%w[]
        },
        {
            "id":138,
            "top":1779,
            "left":1160,
            "surroundings":%w[]
        },
        {
            "id":139,
            "top":1781,
            "left":1130,
            "surroundings":%w[]
        },
        {
            "id":140,
            "top":1842,
            "left":1133,
            "surroundings":%w[ib-block-2]
        },
        {
            "id":141,
            "top":1731,
            "left":1153,
            "surroundings":%w[]
        },
        {
            "id":142,
            "top":1669,
            "left":1177,
            "surroundings":%w[]
        },
        {
            "id":143,
            "top":1671,
            "left":1115,
            "surroundings":%w[]
        },
        {
            "id":144,
            "top":1679,
            "left":887,
            "surroundings":%w[]
        },
        {
            "id":145,
            "top":2060,
            "left":914,
            "surroundings":%w[]
        },
        {
            "id":146,
            "top":2272,
            "left":921,
            "surroundings":%w[cricket-ground]
        },
        {
            "id":147,
            "top":2484,
            "left":925,
            "surroundings":%w[]
        },
        {
            "id":148,
            "top":2582,
            "left":932,
            "surroundings":%w[]
        },
        {
            "id":149,
            "top":2700,
            "left":937,
            "surroundings":%w[]
        },
        {
            "id":150,
            "top":2699,
            "left":1013,
            "surroundings":%w[radio]
        },
        {
            "id":151,
            "top":2810,
            "left":914,
            "surroundings":%w[girls-hostels narmadha ganga girls-basketball-court yamuna kaveri girls-mess north-bhavani middle-bhavani south-bhavani]
        },
        {
            "id":152,
            "top":2820,
            "left":868,
            "surroundings":%w[west-parking girls-visitor-hut]
        },
        {
            "id":153,
            "top":2838,
            "left":443,
            "surroundings":%w[medical-centre]
        },
        {
            "id":154,
            "top":2405,
            "left":436,
            "surroundings":%w[playground-2 playground-3]
        },
        {
            "id":155,
            "top":2071,
            "left":425,
            "surroundings":%w[]
        },
        {
            "id":156,
            "top":2038,
            "left":656,
            "surroundings":%w[football-ground]
        },
        {
            "id":157,
            "top":2850,
            "left":140,
            "surroundings":%w[west-gate]
        },
        {
            "id":158,
            "top": 1651,
            "left": 1761,
            "surroundings":%w[]
        },
        {
            "id":159,
            "top": 1794,
            "left": 1765,
            "surroundings":%w[]
        },
    ]
end

=begin
{
    "id":,
    "top":,
    "left":,
    "surroundings":%w[]
},
=end
