def junctions
    [
        {
            "id":1,
            "top":481,
            "left":1755,
            "surroundings": %w[main-gate]
        },
        {
            "id":2,
            "top":626,
            "left":1767,
            "surroundings": %w[guest-house]
        },
        {
            "id":3,
            "top":861,
            "left":1784,
            "surroundings": []
        },
        {
            "id":4,
            "top":857,
            "left":1859,
            "surroundings": []
        },
        {
            "id":5,
            "top":931,
            "left":1788,
            "surroundings": %w[atm-1]
        },
        {
            "id":6,
            "top":965,
            "left":1861,
            "surroundings": %w[main-parking]
        },
        {
            "id":7,
            "top":1196,
            "left":1805,
            "surroundings": []
        },
        {
            "id":8,
            "top":1195,
            "left":1867,
            "surroundings": []
        },
        {
            "id":9,
            "top":1189,
            "left":2097,
            "surroundings": %w[lake]
        },
        {
            "id":10,
            "top":1254,
            "left":1805,
            "surroundings": []
        },
        {
            "id":11,
            "top":1265,
            "left":1539,
            "surroundings": %w[bus]
        },
        {
            "id":12,
            "top":1293,
            "left":879,
            "surroundings": %w[staff-quarters]
        },
        {
            "id":13,
            "top":1322,
            "left":356,
            "surroundings": %w[west-gate-staffs]
        },
        {
            "id":14,
            "top":1485,
            "left":1550,
            "surroundings": %w[smart-agri-fields]
        },
        {
            "id":15,
            "top":1417,
            "left":1817,
            "surroundings": []
        },
        {
            "id":16,
            "top":1422,
            "left":1912,
            "surroundings": %w[principal-office research-park]
        },
        {
            "id":17,
            "top":1478,
            "left":1820,
            "surroundings":%w[]
        },
        {
            "id":18,
            "top":1474,
            "left":1906,
            "surroundings":%w[]
        },
        {
            "id":19,
            "top":1654,
            "left":1815,
            "surroundings":%w[]
        },
        {
            "id":20,
            "top":1668,
            "left":1993,
            "surroundings":%w[principal-room dean-room]
        },
        {
            "id":21,
            "top":1752,
            "left":1830,
            "surroundings":%w[]
        },
        {
            "id":22,
            "top":1749,
            "left":1995,
            "surroundings":%w[]
        },
        {
            "id":23,
            "top":1821,
            "left":1837,
            "surroundings":%w[]
        },
        {
            "id":24,
            "top":1822,
            "left":2002,
            "surroundings":%w[]
        },
        {
            "id":25,
            "top":1929,
            "left":1924,
            "surroundings":%w[]
        },
        {
            "id":26,
            "top":1932,
            "left":2012,
            "surroundings":%w[sf-block]
        },
        {
            "id":27,
            "top":2001,
            "left":1842,
            "surroundings":%w[]
        },
        {
            "id":28,
            "top":2038,
            "left":1841,
            "surroundings":%w[]
        },
        {
            "id":29,
            "top":2084,
            "left":1846,
            "surroundings":%w[]
        },
        {
            "id":30,
            "top":2072,
            "left":2082,
            "surroundings":%w[]
        },
        {
            "id":31,
            "top":1960,
            "left":2190,
            "surroundings":%w[sf-block-labs]
        },
        {
            "id":32,
            "top":2153,
            "left":1849,
            "surroundings":%w[]
        },
        {
            "id":33,
            "top":2144,
            "left":1923,
            "surroundings":%w[]
        },
        {
            "id":34,
            "top":2179,
            "left":1923,
            "surroundings":%w[mechanic-front]
        },
        {
            "id":35,
            "top":2209,
            "left":1925,
            "surroundings":%w[]
        },
        {
            "id":36,
            "top":2213,
            "left":1855,
            "surroundings":%w[]
        },
        {
            "id":37,
            "top":2255,
            "left":1854,
            "surroundings":%w[]
        },
        {
            "id":38,
            "top":2292,
            "left":1850,
            "surroundings":%w[]
        },
        {
            "id":39,
            "top":2276,
            "left":2119,
            "surroundings":%w[]
        },
        {
            "id":40,
            "top":2221,
            "left":2118,
            "surroundings":%w[mechanic-back]
        },
        {
            "id":41,
            "top":2456,
            "left":1859,
            "surroundings":%w[]
        },
        {
            "id":42,
            "top":2476,
            "left":1862,
            "surroundings":%w[]
        },
        {
            "id":43,
            "top":2473,
            "left":1933,
            "surroundings":%w[]
        },
        {
            "id":44,
            "top":2529,
            "left":1933,
            "surroundings":%w[main-store]
        },
        {
            "id":45,
            "top":2591,
            "left":1935,
            "surroundings":%w[]
        },
        {
            "id":46,
            "top":2548,
            "left":1863,
            "surroundings":%w[]
        },
        {
            "id":47,
            "top":2588,
            "left":1867,
            "surroundings":%w[]
        },
        {
            "id":48,
            "top":2648,
            "left":1871,
            "surroundings":%w[]
        },
        {
            "id":49,
            "top":2797,
            "left":1882,
            "surroundings":%w[]
        },
        {
            "id":50,
            "top":2795,
            "left":1990,
            "surroundings":%w[boys-visitor-hall power-house]
        },
        {
            "id":51,
            "top":2794,
            "left":2042,
            "surroundings":%w[boys-hostels]
        },
        {
            "id":52,
            "top":2727,
            "left":2039,
            "surroundings":%w[indoor-gym]
        },
        {
            "id":53,
            "top":2789,
            "left":2095,
            "surroundings":%w[]
        },
        {
            "id":54,
            "top":2748,
            "left":2132,
            "surroundings":%w[]
        },
        {
            "id":55,
            "top":2721,
            "left":2072,
            "surroundings":%w[outdoor-gym]
        },
        {
            "id":56,
            "top":2711,
            "left":2171,
            "surroundings":%w[]
        },
        {
            "id":57,
            "top":2573,
            "left":2168,
            "surroundings":%w[]
        },
        {
            "id":58,
            "top":2577,
            "left":2068,
            "surroundings":%w[]
        },
        {
            "id":59,
            "top":2578,
            "left":2024,
            "surroundings":%w[coral]
        },
        {
            "id":60,
            "top":2571,
            "left":2236,
            "surroundings":%w[]
        },
        {
            "id":61,
            "top":2786,
            "left":2133,
            "surroundings":%w[]
        },
        {
            "id":62,
            "top":2779,
            "left":2271,
            "surroundings":%w[boys-mess]
        },
        {
            "id":63,
            "top":2567,
            "left":2265,
            "surroundings":%w[emerald]
        },
        {
            "id":64,
            "top":2509,
            "left":2298,
            "surroundings":%w[]
        },
        {
            "id":65,
            "top":2488,
            "left":2657,
            "surroundings":%w[diamond]
        },
        {
            "id":66,
            "top":2955,
            "left":2278,
            "surroundings":%w[sapphire]
        },
        {
            "id":67,
            "top":2971,
            "left":2250,
            "surroundings":%w[]
        },
        {
            "id":68,
            "top":2966,
            "left":2136,
            "surroundings":%w[]
        },
        {
            "id":69,
            "top":2969,
            "left":2085,
            "surroundings":%w[boys-canteen parlour-boys]
        },
        {
            "id":70,
            "top":2873,
            "left":2134,
            "surroundings":%w[boys-laundry]
        },
        {
            "id":71,
            "top":2997,
            "left":2414,
            "surroundings":%w[]
        },
        {
            "id":72,
            "top":2910,
            "left":2591,
            "surroundings":%w[]
        },
        {
            "id":73,
            "top":2902,
            "left":2659,
            "surroundings":%w[]
        },
        {
            "id":74,
            "top":3063,
            "left":2554,
            "surroundings":%w[]
        },
        {
            "id":75,
            "top":3058,
            "left":2691,
            "surroundings":%w[ruby]
        },
        {
            "id":76,
            "top":3057,
            "left":2978,
            "surroundings":%w[]
        },
        {
            "id":77,
            "top":3222,
            "left":2978,
            "surroundings":%w[]
        },
        {
            "id":78,
            "top":3253,
            "left":2914,
            "surroundings":%w[pearl]
        },
        {
            "id":79,
            "top":3290,
            "left":2550,
            "surroundings":%w[]
        },
        {
            "id":80,
            "top":3301,
            "left":2312,
            "surroundings":%w[agri-playground]
        },
        {
            "id":81,
            "top":3313,
            "left":1897,
            "surroundings":%w[playground-1]
        },
        {
            "id":82,
            "top":3100,
            "left":1890,
            "surroundings":%w[tennis-court-1 tennis-court-2 basket-ball-court volley-ball-court]
        },
        {
            "id":83,
            "top":2799,
            "left":1668,
            "surroundings":%w[]
        },
        {
            "id":84,
            "top":2800,
            "left":1615,
            "surroundings":%w[]
        },
        {
            "id":85,
            "top":2807,
            "left":1579,
            "surroundings":%w[]
        },
        {
            "id":86,
            "top":2928,
            "left":1579,
            "surroundings":%w[dayscholar-mess-1 recreation-hall]
        },
        {
            "id":87,
            "top":2919,
            "left":1669,
            "surroundings":%w[dayscholar-mess-2 pet-room cafeteria]
        },
        {
            "id":88,
            "top":2662,
            "left":1610,
            "surroundings":%w[]
        },
        {
            "id":89,
            "top":2610,
            "left":1606,
            "surroundings":%w[fashion-centre spinning-lab]
        },
        {
            "id":90,
            "top":2558,
            "left":1603,
            "surroundings":%w[]
        },
        {
            "id":91,
            "top":2513,
            "left":1603,
            "surroundings":%w[as-rib-11 as-rib-12]
        },
        {
            "id":92,
            "top":2470,
            "left":1600,
            "surroundings":%w[]
        },
        {
            "id":93,
            "top":2433,
            "left":1600,
            "surroundings":%w[as-rib-9 as-rib-10]
        },
        {
            "id":94,
            "top":2338,
            "left":1595,
            "surroundings":%w[]
        },
        {
            "id":95,
            "top":2300,
            "left":1595,
            "surroundings":%w[as-rib-7 as-rib-8]
        },
        {
            "id":96,
            "top":2264,
            "left":1592,
            "surroundings":%w[]
        },
        {
            "id":97,
            "top":2225,
            "left":1590,
            "surroundings":%w[as-rib-5 as-rib-6]
        },
        {
            "id":98,
            "top":2123,
            "left":1585,
            "surroundings":%w[]
        },
        {
            "id":99,
            "top":2086,
            "left":1584,
            "surroundings":%w[as-rib-3 as-rib-4]
        },
        {
            "id":100,
            "top":2050,
            "left":1583,
            "surroundings":%w[]
        },
        {
            "id":101,
            "top":2009,
            "left":1581,
            "surroundings":%w[as-rib-1 as-rib-2]
        },
        {
            "id":102,
            "top":1853,
            "left":1577,
            "surroundings":%w[]
        },
        {
            "id":103,
            "top":1851,
            "left":1610,
            "surroundings":%w[]
        },
        {
            "id":104,
            "top":1809,
            "left":1611,
            "surroundings":%w[as-main-right]
        },
        {
            "id":105,
            "top":1787,
            "left":1608,
            "surroundings":%w[]
        },
        {
            "id":106,
            "top":1787,
            "left":1571,
            "surroundings":%w[]
        },
        {
            "id":107,
            "top":1788,
            "left":1542,
            "surroundings":%w[]
        },
        {
            "id":108,
            "top":1851,
            "left":1539,
            "surroundings":%w[as-main-left]
        },
        {
            "id":109,
            "top":1743,
            "left":1568,
            "surroundings":%w[]
        },
        {
            "id":110,
            "top":1667,
            "left":1609,
            "surroundings":%w[]
        },
        {
            "id":111,
            "top":1669,
            "left":1555,
            "surroundings":%w[]
        },
        {
            "id":112,
            "top":1671,
            "left":1503,
            "surroundings":%w[]
        },
        {
            "id":113,
            "top":1672,
            "left":1366,
            "surroundings":%w[]
        },
        {
            "id":114,
            "top":2133,
            "left":1376,
            "surroundings":%w[]
        },
        {
            "id":115,
            "top":2132,
            "left":1471,
            "surroundings":%w[chiller-plant]
        },
        {
            "id":116,
            "top":2347,
            "left":1393,
            "surroundings":%w[]
        },
        {
            "id":117,
            "top":2443,
            "left":1401,
            "surroundings":%w[main-auditorium]
        },
        {
            "id":118,
            "top":2815,
            "left":1420,
            "surroundings":%w[library]
        },
        {
            "id":119,
            "top":2830,
            "left":1217,
            "surroundings":%w[]
        },
        {
            "id":120,
            "top":2681,
            "left":1215,
            "surroundings":%w[]
        },
        {
            "id":121,
            "top":2638,
            "left":1218,
            "surroundings":%w[placement-and-training internet-centre]
        },
        {
            "id":122,
            "top":2589,
            "left":1217,
            "surroundings":%w[]
        },
        {
            "id":123,
            "top":2523,
            "left":1215,
            "surroundings":%w[ib-rib-12 ib-rib-11]
        },
        {
            "id":124,
            "top":2488,
            "left":1215,
            "surroundings":%w[]
        },
        {
            "id":125,
            "top":2452,
            "left":1212,
            "surroundings":%w[ib-rib-10 ib-rib-9]
        },
        {
            "id":126,
            "top":2353,
            "left":1207,
            "surroundings":%w[]
        },
        {
            "id":127,
            "top":2312,
            "left":1203,
            "surroundings":%w[ib-rib-8 ib-rib-7]
        },
        {
            "id":128,
            "top":2279,
            "left":1201,
            "surroundings":%w[]
        },
        {
            "id":129,
            "top":2242,
            "left":1199,
            "surroundings":%w[ib-rib-6 ib-rib-5]
        },
        {
            "id":130,
            "top":2140,
            "left":1192,
            "surroundings":%w[]
        },
        {
            "id":131,
            "top":2104,
            "left":1190,
            "surroundings":%w[ib-rib-4 ib-rib-3]
        },
        {
            "id":132,
            "top":2069,
            "left":1189,
            "surroundings":%w[]
        },
        {
            "id":133,
            "top":2036,
            "left":1188,
            "surroundings":%w[ib-rib-1 ib-rib-2]
        },
        {
            "id":134,
            "top":1980,
            "left":1184,
            "surroundings":%w[herbal-garden]
        },
        {
            "id":135,
            "top":1865,
            "left":1183,
            "surroundings":%w[]
        },
        {
            "id":136,
            "top":1865,
            "left":1217,
            "surroundings":%w[ib-block-1]
        },
        {
            "id":137,
            "top":1799,
            "left":1212,
            "surroundings":%w[]
        },
        {
            "id":138,
            "top":1800,
            "left":1178,
            "surroundings":%w[]
        },
        {
            "id":139,
            "top":1800,
            "left":1152,
            "surroundings":%w[]
        },
        {
            "id":140,
            "top":1866,
            "left":1150,
            "surroundings":%w[ib-block-2]
        },
        {
            "id":141,
            "top":1764,
            "left":1177,
            "surroundings":%w[]
        },
        {
            "id":142,
            "top":1675,
            "left":1219,
            "surroundings":%w[]
        },
        {
            "id":143,
            "top":1681,
            "left":1120,
            "surroundings":%w[]
        },
        {
            "id":144,
            "top":1696,
            "left":904,
            "surroundings":%w[]
        },
        {
            "id":145,
            "top":2082,
            "left":921,
            "surroundings":%w[]
        },
        {
            "id":146,
            "top":2292,
            "left":933,
            "surroundings":%w[cricket-ground]
        },
        {
            "id":147,
            "top":2501,
            "left":946,
            "surroundings":%w[]
        },
        {
            "id":148,
            "top":2598,
            "left":952,
            "surroundings":%w[]
        },
        {
            "id":149,
            "top":2756,
            "left":961,
            "surroundings":%w[]
        },
        {
            "id":150,
            "top":2751,
            "left":1035,
            "surroundings":%w[radio]
        },
        {
            "id":151,
            "top":2845,
            "left":965,
            "surroundings":%w[girls-hostels]
        },
        {
            "id":152,
            "top":2850,
            "left":858,
            "surroundings":%w[west-parking girls-visitor-hut]
        },
        {
            "id":153,
            "top":2867,
            "left":464,
            "surroundings":%w[medical-centre]
        },
        {
            "id":154,
            "top":2458,
            "left":461,
            "surroundings":%w[playground-2 playground-3]
        },
        {
            "id":155,
            "top":2092,
            "left":443,
            "surroundings":%w[]
        },
        {
            "id":156,
            "top":2082,
            "left":662,
            "surroundings":%w[football-ground]
        },
        {
            "id":157,
            "top":2870,
            "left":173,
            "surroundings":%w[west-gate]
        },
        {
            "id":158,
            "top": 1660,
            "left": 1790,
            "surroundings":%w[]
        },
        {
            "id":159,
            "top": 1808,
            "left": 1794,
            "surroundings":%w[]
        },
        {
            "id":160,
            "top":3002,
            "left":971,
            "surroundings":%w[]
        },
        {
            "id":161,
            "top":3087,
            "left":974,
            "surroundings":%w[]
        },
        {
            "id":162,
            "top":3085,
            "left":926,
            "surroundings":%w[]
        },
        {
            "id":163,
            "top":3091,
            "left":871,
            "surroundings":%w[]
        },
        {
            "id":164,
            "top":3085,
            "left":1009,
            "surroundings":%w[]
        },
        {
            "id":165,
            "top":3082,
            "left":1071,
            "surroundings":%w[]
        },
        {
            "id":166,
            "top":3008,
            "left":783,
            "surroundings":%w[canteen-girls]
        },
        {
            "id":167,
            "top":3022,
            "left":512,
            "surroundings":%w[]
        },
        {
            "id":168,
            "top":3134,
            "left":515,
            "surroundings":%w[]
        },
        {
            "id":169,
            "top":3135,
            "left":562,
            "surroundings":%w[narmadha]
        },
        {
            "id":170,
            "top":3272,
            "left":928,
            "surroundings":%w[throwball-court-girls]
        },
        {
            "id":171,
            "top":3270,
            "left":974,
            "surroundings":%w[girls-basketball-court]
        },
        {
            "id":172,
            "top":3269,
            "left":1015,
            "surroundings":%w[volleyball-court-girls]
        },
        {
            "id":173,
            "top":3315,
            "left":937,
            "surroundings":%w[]
        },
        {
            "id":174,
            "top":3300,
            "left":977,
            "surroundings":%w[]
        },
        {
            "id":175,
            "top":3302,
            "left":1016,
            "surroundings":%w[]
        },
        {
            "id":176,
            "top":3353,
            "left":987,
            "surroundings":%w[]
        },
        {
            "id":177,
            "top":3312,
            "left":563,
            "surroundings":%w[]
        },
        {
            "id":178,
            "top":3461,
            "left":1116,
            "surroundings":%w[]
        },
        {
            "id":179,
            "top":3458,
            "left":1239,
            "surroundings":%w[middle-bhavani laundry-girls]
        },
        {
            "id":180,
            "top":3400,
            "left":1237,
            "surroundings":%w[north-bhavani]
        },
        {
            "id":181,
            "top":3535,
            "left":1242,
            "surroundings":%w[south-bhavani]
        },
        {
            "id": 182,
            "top":3302,
            "left":826,
            "surroundings":%w[]
        },
        {
            "id":183,
            "top":3403,
            "left":830,
            "surroundings":%w[kaveri]
        },
        {
            "id":184,
            "top":3511,
            "left":879,
            "surroundings":%w[parlour-girls]
        },
        {
            "id":185,
            "top":3309,
            "left":910,
            "surroundings":%w[]
        },
        {
            "id":186,
            "top":3396,
            "left":990,
            "surroundings":%w[girls-mess dance-hall girls-gym]
        },
        {
            "id":187,
            "top":3356,
            "left":909,
            "surroundings":%w[]
        },
        {
            "id":188,
            "top":3351,
            "left":1071,
            "surroundings":%w[]
        },
        {
            "id":189,
            "top":3391,
            "left":1072,
            "surroundings":%w[]
        },
        {
            "id":190,
            "top":3390,
            "left":1122,
            "surroundings":%w[outdoor-gym-3]
        },
        {
            "id":191,
            "top":3124,
            "left":871,
            "surroundings":%w[]
        },
        {
            "id":192,
            "top":3124,
            "left":821,
            "surroundings":%w[]
        },
        {
            "id":193,
            "top":3112,
            "left":1075,
            "surroundings":%w[]
        },
        {
            "id":194,
            "top":3110,
            "left":1255,
            "surroundings":%w[]
        },
        {
            "id":195,
            "top":3093,
            "left":1174,
            "surroundings":%w[]
        },
        {
            "id":196,
            "top":3253,
            "left":1121,
            "surroundings":%w[]
        },
        {
            "id":197,
            "top":3400,
            "left":874,
            "surroundings":%w[outdoor-gym-2]
        },
        {
            "id":198,
            "top":3210,
            "left":817,
            "surroundings":%w[ganga]
        },
        {
            "id":199,
            "top":3183,
            "left":1255,
            "surroundings":%w[]
        },
        {
            "id":200,
            "top":3240,
            "left":1253,
            "surroundings":%w[yamuna]
        },
        {
            "id":201,
            "top":3241,
            "left":1133,
            "surroundings":%w[]
        },
    ]
end

=begin
{
    "id":,
    "top":,
    "left":,
    "surroundings":%w[]
},
=end
